title: "PU"
email: priyankau@abc.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "https://PriyankaUtekar@github.io/"
twitter_username: priyankau
github_username:  priyankau

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg

theme: jekyll-theme-minimal